server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.102.147.246:3306/offerSpring?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: wxp1135...
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.offer.model


