server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.102.147.246:3306/offerSpring?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: wxp1135...
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    check-template-location: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.offer.model



